# If we don't handle exception then it will not execute next statement after getting exceptions.

first_number = int(input("Enter first number : "))
second_number = int(input("Enter second number : "))

div = first_number/second_number
print("div : {}".format(div))

# statement
print("I am learning python.")